### ISSUE TITLE
stata-gtools

### ISSUE THREAD

**Issue by matthieugomez** [matthieugomez/benchmark-stata-r#6]
Use [stata-gtools](https://github.com/mcaceresb/stata-gtools) for collapse + egen instructions once weights + MAC OSX compilations are implemented @mcaceresb

**Comment by mcaceresb** [comment]
@matthieugomez: Would you be willing to help compile gtools on OSX? My previous plan to get access to an OSX machine fell through and I don't otherwise have access to Apple hardware. I have tried to test the code on a server running  OSX via Travis CI, but it's a bit difficult to debug that way (not to mention those servers don't have Stata).

No worries if you don't have the time (and If the code base proves buggy on OSX I won't press too much), but let me know either way.

**Comment by mcaceresb** [comment]
I've had an OSX version for some time, and weights have been recently implemented. Further, several new commands are available (e.g. gdistinct for distinct, gquantiles for pctile and xtile).

**Comment by matthieugomez** [comment]
Looks great! How to install it on MacOSX? I tried
```
local github "https://raw.githubusercontent.com"
net install gtools, from(`github'/mcaceresb/stata-gtools/master/build/)
```
But I got
```
could not copy https://raw.githubusercontent.com/mcaceresb/stata-gtools/master/build/fasterxtile.sthlp
--Break--
r(1);
```

**Comment by mcaceresb** [comment]
I'm a bit baffled. if you go to the link for `fasterxtile.sthlp`, it's the same file I have locally; I also tested it just yesterday on StataSE 14 on an iMac (and prior I had tested on StataIC 13). One thing that occurs to me is that `fasterxtile.sthlp` redirects to `gquantiles.sthlp`, which is downloaded _after_ and maybe that's why it trips? Try:

```stata
local github "https://raw.githubusercontent.com"
net install gtools, from(`github'/mcaceresb/stata-gtools/develop/build/)
```

If that works I'll merge with master. If it doesn't, I'm actually not sure what to do about it...

**Comment by matthieugomez** [comment]
All right I rerun the benchmarks with your commands. Really cool work! 
Is there a reason you chose the syntax `gquantiles, xtile` and `gquantiles, _pctile` rather than  `gegen temp = xtile` and `gegen temp = _gpctile`?

**Comment by mcaceresb** [comment]
There are a lot of reasons, but mainly it's that `egen` works as a syntax wrapper; it doesn't really do anything in terms of speed or ease of implementing a function. `gegen` does do more than just being a syntax wrapper, but even then it's still a wrapper of some sort. So even if from a user POV it's nicer to call `gegen xtile` or `gegen pctile`, internally it would have been inefficient and messy to code.

I can elaborate if you are interested about how gtools and Stata plugins work internally and the features I wanted in `gquantiles`, but that's the gist of it.

**Comment by jmboehm** [comment]
Dear Internet: if you come across the same funny error message as `matthieugomez`,
```
could not copy https://raw.githubusercontent.com/mcaceresb/stata-gtools/master/build/fasterxtile.sthlp
--Break--
r(1);
```
then download the whole repo to your local drive and install it from there:
```
net install gtools, from(local-path-to-stata-gtools-master/build/)
```
That works for me at least.

**Comment by matthieugomez** [comment]
I've just added `gtools` to the benchmark. Great work!
